# Generated by Django 6.0.2 on 2026-02-23 22:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Brouillon'), ('Pending', 'En attente'), ('In Progress', 'En cours'), ('Completed', 'Terminé'), ('Archived', 'Archivé')], default='Draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(related_name='projects', to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('Feature', 'Fonctionnalité'), ('Bug', 'Bug'), ('Task', 'Tâche'), ('Run', 'Exécution'), ('Deliverable', 'Livrable'), ('Other', 'Autre')], default='Task', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Faible'), ('Medium', 'Moyen'), ('High', 'Haute'), ('Critical', 'Critique')], default='Low', max_length=20)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='projects_pr_status_e848a9_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'task_type'], name='projects_pr_project_d8d752_idx'),
        ),
    ]
