# Generated by Django 6.0.2 on 2026-02-25 21:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('allocation_type', models.CharField(choices=[('Percentage', 'Pourcentage'), ('Hours per Day', 'Heures par jour')], default='Hours per Day', max_length=20)),
                ('allocation_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project')),
                ('project_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='projects.projecttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date_start', 'date_end', 'user'], name='planning_as_date_st_a862da_idx'), models.Index(fields=['project', 'date_start', 'date_end'], name='planning_as_project_bcf859_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_end__gte', models.F('date_start'))), name='assignment_date_end_gte_date_start'), models.CheckConstraint(condition=models.Q(('allocation_value__gte', 0)), name='assignment_allocation_value_gte_0')],
            },
        ),
    ]
